services:
    opencats:
      container_name: opencats_web
      image: prooph/nginx:www
      ports:
          - "80:80"
          - "443:443"
      volumes_from:
        - opencatsdata

    php:
      container_name: opencats_php
      build:
        context: ..
        dockerfile: docker/php/Dockerfile
      volumes_from:
        - opencatsdata
      volumes:
        - ./php/conf.d/zz-opencats.ini:/usr/local/etc/php/conf.d/zz-opencats.ini:ro

    opencatsdata:
      container_name: opencats_data
      image: busybox
      volumes:
        - ..:/var/www/public
      command: "true"

    opencatsdb:
      container_name: opencats_mariadb
      image: mariadb
      ports:
        - 3306:3306
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_USER=dev
        - MYSQL_PASSWORD=dev
        - MYSQL_DATABASE=cats
      volumes:
        - ../db/cats_schema.sql:/docker-entrypoint-initdb.d/000_schema.sql:ro
        - ../db/cats_demo_data.sql:/docker-entrypoint-initdb.d/001_demo.sql:ro
        - ./persist/mysql:/var/lib/mysql

    phpmyadmin:
      container_name: opencats_phpmyadmin
      image: phpmyadmin/phpmyadmin
      ports:
        - 8080:80
      links:
        - opencatsdb:db
      environment:
        - PMA_HOST=db
        - PMA_USER=dev
        - PMA_PASSWORD=dev
