/* WTF Gyms career portal template. Idempotent: safe to re-run.
   Rendered by modules/careers/Blank.tpl as:
     <head><style>{CSS}</style></head><body>{Header}{Content}{Footer}{Powered by OpenCATS}
   NOTE: "Content - Apply for Position" must contain NO <td> elements. CareersUI.php:768
   strips everything before the first <td> on that page. */

SET NAMES utf8mb4;

DELETE FROM career_portal_template_site WHERE career_portal_name = 'WTF Gyms';

INSERT INTO career_portal_template_site (career_portal_name, setting, value) VALUES ('WTF Gyms', 'CSS', '
*{box-sizing:border-box}
html,body{margin:0;padding:0;background:#ffffff;color:#16161a;font:400 15px/1.65 "Inter",-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;-webkit-font-smoothing:antialiased}
a{color:#D2000B;text-decoration:none}
a:hover{color:#D2000B;text-decoration:underline}
img{border:none;max-width:100%}
h1,h2,h3{margin:0 0 12px 0;line-height:1.2;color:#0f0f12}
h1{font:800 34px/1.15 "Arial Black","Helvetica Neue",Helvetica,Arial,sans-serif;letter-spacing:-0.5px}
h2{font:700 20px/1.3 Arial,Helvetica,sans-serif}
h3{font:700 16px/1.3 Arial,Helvetica,sans-serif}
p{margin:0 0 12px 0}
.wrap{max-width:1060px;margin:0 auto;padding:0 22px}
.muted{color:#6b6b70}

/* HEADER */
.site-header{background:#0A0A0A;border-bottom:3px solid #D2000B;position:sticky;top:0;z-index:50}
.brand-logo{height:34px;width:auto;display:block}
.hdr{display:flex;align-items:center;justify-content:space-between;min-height:64px;gap:16px;flex-wrap:wrap}
.brand{display:flex;align-items:center;gap:11px;color:#ffffff}
.brand:hover{color:#ffffff;text-decoration:none}
.brand-sub{font:700 12px/1 Arial,Helvetica,sans-serif;letter-spacing:2.4px;text-transform:uppercase;color:#b8b8bd}
.hdr-nav{display:flex;gap:22px;align-items:center;font:600 13px/1 Arial,Helvetica,sans-serif;letter-spacing:.4px;text-transform:uppercase}
.hdr-nav a{color:#d4d4d8}
.hdr-nav a:hover{color:#ffffff;text-decoration:none}

/* BUTTONS */
.btn{display:inline-block;background:#D2000B;color:#ffffff !important;font:700 14px/1 Arial,Helvetica,sans-serif;letter-spacing:.4px;padding:14px 26px;border-radius:6px;border:none;cursor:pointer;text-transform:uppercase}
.btn:hover{background:#A80009;color:#ffffff !important;text-decoration:none}
.btn-lg{padding:16px 34px;font-size:15px}

/* HERO */
.hero{padding:64px 0 44px 0;border-bottom:1px solid #e3e3e6}
.eyebrow{font:700 12px/1 Arial,Helvetica,sans-serif;letter-spacing:3px;text-transform:uppercase;color:#D2000B;margin:0 0 16px 0}
.hero h1{font-size:46px;max-width:16em}
.hero .hl{color:#D2000B}
.lede{font-size:17px;color:#44444a;max-width:44em;margin:16px 0 28px 0}
.stat{display:inline-flex;align-items:center;gap:9px;margin-left:18px;color:#6b6b70;font-size:14px}
.dot{width:8px;height:8px;border-radius:50%;background:#12a150;display:inline-block}

.section{padding:44px 0}
.verticals{list-style:none;margin:0 0 16px 0;padding:0;display:flex;flex-wrap:wrap;gap:10px}
.verticals li{background:#f4f4f5;border:1px solid #e3e3e6;border-radius:999px;padding:9px 16px;font-size:14px;font-weight:600;color:#3d3d42}
.page-head{padding:44px 0 22px 0}
.crumb{padding:26px 0 0 0;font-size:14px}
.card{background:#fafafa;border:1px solid #e3e3e6;border-radius:10px;padding:26px;margin:0 0 22px 0}

/* JOB LIST TABLE (markup generated by CareersUI::getResultsTable) */
.table-wrap{background:#ffffff;border:1px solid #e3e3e6;border-radius:10px;overflow-x:auto;margin-bottom:40px}
table.sortable{width:100%;border-collapse:collapse;text-align:left;empty-cells:show;font-size:15px}
table.sortable th{padding:15px 18px;font:700 11px/1 Arial,Helvetica,sans-serif;letter-spacing:1.6px;text-transform:uppercase;color:#6b6b70;white-space:nowrap}
table.sortable td{padding:16px 18px;vertical-align:middle;border-top:1px solid #ececef}
tr.rowHeading{background:#f4f4f5;border:none}
tr.evenTableRow{background:#ffffff}
tr.oddTableRow{background:#fbfbfc}
tr.evenTableRow:hover,tr.oddTableRow:hover{background:#FBF3F3}
table.sortable td a{font-weight:700}
a.sortheader,a.sortheader:link,a.sortheader:visited{color:#6b6b70}
a.sortheader:hover{color:#D2000B}

/* JOB DETAILS */
.job-head{padding:22px 0 30px 0;border-bottom:1px solid #e3e3e6;margin-bottom:30px}
.chips{margin:0 0 24px 0;display:flex;gap:10px;flex-wrap:wrap}
.chip{display:inline-block;background:#f4f4f5;border:1px solid #e3e3e6;color:#44444a;border-radius:999px;padding:7px 15px;font-size:13px}
.job-desc{line-height:1.75;color:#33333a}
.job-desc p{margin:0 0 14px 0}
.apply-foot{padding:12px 0 60px 0}

/* FORMS
   OpenCATS emits its text fields as <input name="x" class="inputBoxNormal">
   with NO type attribute, so an input[type=text] selector never matches them.
   Match the bare inputs and the CATS classes explicitly. */
.form-grid{display:flex;flex-wrap:wrap;gap:22px;margin:0 0 8px 0}
.form-col{flex:1 1 420px;min-width:300px}
.field{margin:0 0 16px 0}
.field label{display:block;margin:0 0 7px 0;font:700 12px/1 Arial,Helvetica,sans-serif;letter-spacing:.8px;text-transform:uppercase;color:#44444a}
input:not([type]),input[type=text],input[type=email],input[type=password],input[type=tel],input[type=file],
.inputBoxName,.inputBoxNormal,.inputBoxArea,select,textarea{width:100%;background:#ffffff;border:1px solid #c9c9cf;border-radius:6px;color:#16161a;padding:12px 13px;font:400 15px/1.4 Arial,Helvetica,sans-serif}
input:not([type]):focus,input[type=text]:focus,input[type=email]:focus,
.inputBoxName:focus,.inputBoxNormal:focus,.inputBoxArea:focus,select:focus,textarea:focus{outline:none;border-color:#D2000B;box-shadow:0 0 0 3px rgba(210,0,11,.15)}
textarea{min-height:120px;resize:vertical}
input[type=file]{padding:9px 11px;cursor:pointer}
input[type=checkbox],input[type=radio]{width:auto;margin-right:8px}
input[type=button]{background:#ffffff;color:#44444a;border:1px solid #c9c9cf;border-radius:6px;padding:10px 16px;font:600 13px/1 Arial,Helvetica,sans-serif;cursor:pointer;width:auto}
input[type=button]:hover{border-color:#D2000B;color:#D2000B}
input[type=submit],.submitButton{background:#D2000B;color:#ffffff;font:700 14px/1 Arial,Helvetica,sans-serif;letter-spacing:.4px;text-transform:uppercase;padding:14px 30px;border:none;border-radius:6px;cursor:pointer;width:auto}
input[type=submit]:hover,.submitButton:hover{background:#A80009}
.instructions{color:#6b6b70;font-size:13px;font-style:italic}
.req{color:#D2000B}

/* FOOTER */
.site-footer{border-top:1px solid #e3e3e6;margin-top:40px;padding:34px 0;color:#6b6b70;font-size:14px}
.site-footer a{color:#44444a}
.site-footer a:hover{color:#D2000B}
#poweredCATS{opacity:.55}
#poweredCATS:hover{opacity:1}

@media (max-width:640px){
  h1{font-size:28px}
  .hero{padding:40px 0 30px 0}
  .hero h1{font-size:32px}
  .form-col{min-width:100%}
  table.sortable th,table.sortable td{padding:12px 12px}
}
');

INSERT INTO career_portal_template_site (career_portal_name, setting, value) VALUES ('WTF Gyms', 'Header', '
<header class="site-header"><div class="wrap hdr">
  <a class="brand" href="index.php"><img src="/images/wtf-logo.png" alt="WTF" class="brand-logo" /><span class="brand-sub">Careers</span></a>
  <nav class="hdr-nav">
    <a href="index.php?m=careers&amp;p=showAll">All Openings</a>
    <a href="https://www.wtfgyms.com" target="_blank" rel="noopener noreferrer">wtfgyms.com</a>
    <a href="<rssURL>">RSS</a>
  </nav>
</div></header>
');

INSERT INTO career_portal_template_site (career_portal_name, setting, value) VALUES ('WTF Gyms', 'Footer', '
<footer class="site-footer"><div class="wrap">
  <p><strong style="color:#0f0f12;">WTF</strong> &mdash; eleven businesses. One place to apply to all of them.</p>
  <p>Every open role across the group is listed here. <a href="index.php?m=careers&amp;p=showAll">Browse openings</a> or visit <a href="https://www.wtfgyms.com" target="_blank" rel="noopener noreferrer">wtfgyms.com</a>.</p>
  <p style="margin-top:20px;font-size:13px;"><a href="/login">WTF staff login</a></p>
</div></footer>
');

INSERT INTO career_portal_template_site (career_portal_name, setting, value) VALUES ('WTF Gyms', 'Content - Main', '
<div id="careerContent" class="wrap">
  <registeredCandidate>
  <section class="hero">
    <p class="eyebrow">Careers at WTF</p>
    <h1>Eleven businesses. <span class="hl">One team.</span></h1>
    <p class="lede">Most people know WTF for the gyms. That is one of eleven businesses we run under Witness the Fitness Private Limited &mdash; training floors, equipment, an academy, media, recovery, nutrition, and the teams that hold it all together.</p>
    <p class="lede">Which means the work here is not one kind of work. Trainers and physiotherapists, yes &mdash; and marketers, engineers, category managers, technicians and finance people alongside them. Pick the business that fits you.</p>
    <p>
      <a class="btn btn-lg" href="index.php?m=careers&amp;p=showAll">View open roles</a>
      <span class="stat"><span class="dot"></span><numberOfOpenPositions> positions open right now</span>
    </p>
  </section>
  <section class="section">
    <p class="eyebrow">The eleven</p>
    <ul class="verticals"><li>WTF Gyms</li><li>WTF Powered Gyms</li><li>WTF Franchisee Gyms</li><li>WTF Academy</li><li>WTF Amplify</li><li>WTF Reboot</li><li>WTF Go</li><li>WTF Metabolic</li><li>WTF Everyday</li><li>WTF Equipments</li><li>WTF Enterprise</li></ul>
    <p class="muted">Every opening below is tagged with the business it sits in, so you can see exactly what you would be joining.</p>
  </section>
  <section class="section">
    <registeredLoginTitle><h2>Applied with us before?</h2></registeredLoginTitle><registeredLogin>
  </section>
</div>
');

INSERT INTO career_portal_template_site (career_portal_name, setting, value) VALUES ('WTF Gyms', 'Content - Search Results', '
<div id="careerContent" class="wrap">
  <registeredCandidate>
  <div class="page-head">
    <p class="eyebrow">Open roles</p>
    <h1>Current openings</h1>
    <p class="muted"><numberOfSearchResults> position(s) currently accepting applications. Click a role to read the details and apply.</p>
  </div>
  <div class="table-wrap">
<searchResultsTable>
  </div>
</div>
');

INSERT INTO career_portal_template_site (career_portal_name, setting, value) VALUES ('WTF Gyms', 'Content - Job Details', '
<div id="careerContent" class="wrap">
  <registeredCandidate>
  <p class="crumb"><a href="index.php?m=careers&amp;p=showAll">&larr; All openings</a></p>
  <div class="job-head">
    <p class="eyebrow">Open role</p>
    <h1><title></h1>
    <div class="chips">
      <span class="chip"><location></span>
      <span class="chip"><type></span>
      <span class="chip"><openings> opening(s)</span>
      <span class="chip">Posted <created></span>
    </div>
    <a-applyToJob class="btn btn-lg">Apply for this role</a>
  </div>
  <div class="card job-desc">
    <h2>About the role</h2>
    <description>
  </div>
  <div class="apply-foot"><a-applyToJob class="btn">Apply now</a></div>
</div>
');

/* No <td> anywhere in this section on purpose. See header note. */
INSERT INTO career_portal_template_site (career_portal_name, setting, value) VALUES ('WTF Gyms', 'Content - Apply for Position', '
<div id="careerContent" class="wrap">
  <div class="page-head">
    <p class="eyebrow">Application</p>
    <h1>Apply: <title></h1>
    <p class="instructions">Fields marked <span class="req">*</span> are required. Upload your CV and we will fill in what we can for you.</p>
  </div>

  <div class="card">
    <h3>1. Upload your CV or resume</h3>
    <input-resumeUploadPreview>
  </div>

  <div class="form-grid">
    <div class="form-col">
      <div class="card">
        <h3>2. About you</h3>
        <div class="field"><label for="firstName">First name <span class="req">*</span></label><input-firstName></div>
        <div class="field"><label for="lastName">Last name <span class="req">*</span></label><input-lastName></div>
        <div class="field"><label for="email">Email address <span class="req">*</span></label><input-email></div>
        <div class="field"><label for="emailconfirm">Confirm email <span class="req">*</span></label><input-emailconfirm></div>
        <div class="field"><label for="keySkills">Key skills <span class="req">*</span></label><input-keySkills></div>
      </div>
    </div>
    <div class="form-col">
      <div class="card">
        <h3>3. How we reach you</h3>
        <div class="field"><label for="phoneCell">Mobile number</label><input-phone-cell></div>
        <div class="field"><label for="phoneHome">Alternate number</label><input-phone-home></div>
        <div class="field"><label for="bestTimeToCall">Best time to call <span class="req">*</span></label><input-best-time-to-call></div>
        <div class="field"><label for="address">Address</label><input-address></div>
        <div class="field"><label for="city">City <span class="req">*</span></label><input-city></div>
        <div class="field"><label for="state">State <span class="req">*</span></label><input-state></div>
        <div class="field"><label for="country">Country</label><input-country></div>
        <div class="field"><label for="zip">PIN code <span class="req">*</span></label><input-zip></div>
      </div>
    </div>
  </div>

  <div class="card">
    <h3>4. Anything else we should know?</h3>
    <div class="field"><label for="extraNotes">Notes for the hiring team</label><input-extraNotes></div>
    <div class="field"><label for="captcha">Verification <span class="req">*</span></label><input-captcha req></div>
  </div>

  <div class="apply-foot">
    <input type="submit" class="submitButton" value="Submit application" />
  </div>
</div>
');

INSERT INTO career_portal_template_site (career_portal_name, setting, value) VALUES ('WTF Gyms', 'Content - Thanks for your Submission', '
<div id="careerContent" class="wrap">
  <div class="hero">
    <p class="eyebrow">Application received</p>
    <h1>Thanks &mdash; we have got it.</h1>
    <p class="lede">Your application for <strong><title></strong> is in. A confirmation email is on its way from HR@wtfgyms.com &mdash; check your spam folder if you do not see it. Our hiring team reviews every application and will reach out if there is a fit.</p>
    <p><a class="btn" href="index.php?m=careers&amp;p=showAll">Browse more openings</a></p>
  </div>
</div>
');

INSERT INTO career_portal_template_site (career_portal_name, setting, value) VALUES ('WTF Gyms', 'Content - Questionnaire', '
<div id="careerContent" class="wrap">
  <div class="page-head">
    <p class="eyebrow">A few questions</p>
    <h1>Tell us a bit more</h1>
  </div>
  <div class="card">
<questionnaire>
  </div>
  <div class="apply-foot"><submit value="Continue"></div>
</div>
');

INSERT INTO career_portal_template_site (career_portal_name, setting, value) VALUES ('WTF Gyms', 'Content - Candidate Registration', '
<div id="careerContent" class="wrap">
  <div class="page-head">
    <h1><applyContent>Applying to <title></applyContent></h1>
  </div>
  <div class="card" style="max-width:560px;">
    <div class="field"><label for="email">Your email address</label><input-email></div>
    <div class="field">
      <applyContent>
      <label><input-new> I have not applied here before</label>
      </applyContent>
    </div>
    <div class="field">
      <label><input-registered> I have applied before</label>
      <div style="margin-top:12px;">
        <div class="field"><label for="lastName">Last name</label><input-lastName></div>
        <div class="field"><label for="zip">PIN code</label><input-zip></div>
        <label style="text-transform:none;letter-spacing:0;font-weight:400;color:#6b6b70;"><input-rememberMe> Remember me on this device</label>
      </div>
    </div>
    <div style="margin-top:18px;"><input-submit></div>
  </div>
</div>
');

INSERT INTO career_portal_template_site (career_portal_name, setting, value) VALUES ('WTF Gyms', 'Content - Candidate Profile', '
<div id="careerContent" class="wrap">
  <div class="page-head">
    <p class="eyebrow">Your profile</p>
    <h1>My profile</h1>
    <p class="muted">Changes here apply to every role you have applied for, past and future.</p>
  </div>
  <div class="form-grid">
    <div class="form-col">
      <div class="card">
        <h3>About you</h3>
        <div class="field"><label for="firstName">First name <span class="req">*</span></label><input-firstName></div>
        <div class="field"><label for="lastName">Last name <span class="req">*</span></label><input-lastName></div>
        <div class="field"><label for="email1">Email address <span class="req">*</span></label><input-email1></div>
        <div class="field"><label for="keySkills">Key skills <span class="req">*</span></label><input-keySkills></div>
        <div class="field"><input-resume></div>
      </div>
    </div>
    <div class="form-col">
      <div class="card">
        <h3>How we reach you</h3>
        <div class="field"><label for="phoneCell">Mobile number</label><input-phoneCell></div>
        <div class="field"><label for="phoneHome">Alternate number</label><input-phoneHome></div>
        <div class="field"><label for="phoneWork">Work number</label><input-phoneWork></div>
        <div class="field"><label for="bestTimeToCall">Best time to call <span class="req">*</span></label><input-bestTimeToCall></div>
        <div class="field"><label for="address">Address</label><input-address></div>
        <div class="field"><label for="city">City <span class="req">*</span></label><input-city></div>
        <div class="field"><label for="state">State <span class="req">*</span></label><input-state></div>
        <div class="field"><label for="country">Country</label><input-country></div>
        <div class="field"><label for="zip">PIN code <span class="req">*</span></label><input-zip></div>
        <div style="margin-top:18px;"><input-submit></div>
      </div>
    </div>
  </div>
</div>
');

/* Activate the board. */
UPDATE settings SET value = 'WTF Gyms' WHERE settings_type = 4 AND setting = 'activeBoard';
INSERT INTO settings (settings_type, setting, value)
SELECT 4, 'activeBoard', 'WTF Gyms' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM (SELECT settings_type, setting FROM settings) s
                  WHERE s.settings_type = 4 AND s.setting = 'activeBoard');

SELECT setting, LENGTH(value) AS bytes FROM career_portal_template_site WHERE career_portal_name = 'WTF Gyms' ORDER BY setting;
SELECT setting, value FROM settings WHERE settings_type = 4 AND setting = 'activeBoard';
